services:
  nuxt:
    build:
      context: /home/simon/repos/mailmaster/src/nuxt
      dockerfile: /home/simon/repos/mailmaster/environments/dev/Dockerfile
    ports:
      - "8400:8400"
    volumes:
      - /home/simon/repos/mailmaster/src/nuxt/app:/app/app
      - /home/simon/repos/mailmaster/src/nuxt/nuxt.config.ts:/app/nuxt.config.ts
    env_file:
      - path: /home/simon/repos/mailmaster/environments/dev/.env
        required: true
    environment:
      - NODE_ENV=development

  go-api:
    build:
      context: /home/simon/repos/mailmaster/src/go
      dockerfile: /home/simon/repos/mailmaster/environments/dev/Dockerfile-go
    command: ["/app/mailagent", "-addr=:8401"]
    ports:
      - "8401:8401"
    env_file:
      - path: /home/simon/repos/mailmaster/environments/dev/.env
        required: true

  go-mcp:
    build:
      context: /home/simon/repos/mailmaster/src/go
      dockerfile: /home/simon/repos/mailmaster/environments/dev/Dockerfile-go
    command: ["/app/mailagent", "-addr=:8402"]
    ports:
      - "8402:8402"
    env_file:
      - path: /home/simon/repos/mailmaster/environments/dev/.env
        required: true
